language: python

python:
  - "3.6.5"

install:
  - pip install -r requirements.txt

service:
  - postgresql

before_script:
  - createdb travis;

script:
  - python3 -m unittest
  - pytest --cov=tests

after_success:
  - coveralls

cache: pip